# https://kubernetes.io/docs/concepts/services-networking/ingress/

apiVersion: 'networking.k8s.io/v1beta1'
kind: 'Ingress'
metadata:
  name: 'registry-ingress'
  labels:
    app: 'registry'

  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: 'websecure'

spec:
  # Registry requires SSL protection. Generate a self-signed certificate.
  # This
  tls:
  - hosts:
      - 'registry.local'
  rules:
  - host: 'registry.local'
    http:
      paths:
      - path: '/'
        backend:
          serviceName: 'registry'
          servicePort: 5000
