apiVersion: 'apps/v1'
kind: 'Deployment'
metadata:
  name: 'registry-deployment'
  labels:
    app: 'registry'

spec:
  # Currently limited to 1 replica.
  # Scaling would require determining how to keep replicas consistent.
  replicas: 1
  selector:
    matchLabels:
      app: 'registry'
  template:
    metadata:
      labels:
        app: 'registry'
    spec:
      containers:
        - name: 'registry'
          image: 'registry:2.7.1'
          ports:
            - containerPort: 5000
