# https://kubernetes.io/docs/concepts/services-networking/ingress/

apiVersion: 'networking.k8s.io/v1beta1'
kind: 'Ingress'
metadata:
  name: '{{ .Release.Name }}-jenkins-ingress'
  labels:
    app: '{{ .Release.Name }}-jenkins'

  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: 'websecure'

spec:
  rules:
  - http:
      paths:
      - path: '/jenkins'
        backend:
          serviceName: '{{ .Release.Name }}-jenkins'
          servicePort: 8080
