# Path to the Helmfile relative to location of this helmfile-config.yaml
helmfile: 'helmfile.yaml'

# Dependencies to be uploaded so they can be referenced as local files
dependencies:
  - file: '../../.staging/helm_repo/helm-nginx-0.1.0.tgz'
    destination: 'helm/helm-nginx.tgz'
