version: 0.2

env:
  shell: "bash"

phases:
  pre_build:
    on-failure: "ABORT"
    commands:
      # Load environment variables and secrets
      - 'test -f ./codebuild_env.sh && source ./codebuild_env.sh'
      - 'test -f ./codebuild_secrets.sh && source ./codebuild_secrets.sh'
      # Login to Docker, required due to rate limits on public images
      - 'docker login
           -u $DOCKER_ACCOUNT
           -p $DOCKER_PASSWORD
        '
  build:
    on-failure: "ABORT"
    commands:
      # Build the image
      - 'docker build
           --build-arg "GIT_REPOSITORY=$GIT_REPOSITORY"
           --build-arg "GIT_REPOSITORY_BRANCH=$GIT_REPOSITORY_BRANCH"
           .
        '
