apiVersion: v2
type: application

name: ingress
description: Basic environment for ingress, including cert-manager and Traefik.

# Chart version, expected to follow Semantic Versioning <https://semver.org/>
version: 0.5.0

dependencies:
  # Traefik for ingress
  - name: traefik
    # Prefer an exact version for safety
    version: 9.12.3
    repository: https://helm.traefik.io/traefik
  # cert-manager for certificates
  - name: cert-manager
    # Prefer an exact version for safety
    version: 1.5.3
    repository: https://charts.jetstack.io
