apiVersion: v2
type: application

name: ingress
description: Basic environment for ingress

# Chart version, expected to follow Semantic Versioning <https://semver.org/>
version: 0.1.0

dependencies:
  # Traefik for ingress
  - name: traefik
    version: ~9.11.0
    repository: https://helm.traefik.io/traefik
  # cert-manager for certificates
  - name: cert-manager
    version: ~1.0.4
    repository: https://charts.jetstack.io
