apiVersion: v2
type: application

name: ingress
description: Basic environment for ingress, including cert-manager and Traefik.

# Chart version, expected to follow Semantic Versioning <https://semver.org/>
version: 0.6.0

dependencies:
  # Traefik for ingress
  - name: traefik
    # Specify an exact version for safety
    version: 10.6.1
    repository: https://helm.traefik.io/traefik
