cert-manager:
  # Configure based on:
  # https://github.com/jetstack/cert-manager/blob/master/deploy/charts/cert-manager/values.yaml

  # As of 1.5.3, causes webhook issues because full name includes release name.
  fullnameOverride: 'cert-manager'

  # As of 1.5.3, failing with behavior similar to here:
  # https://github.com/jetstack/cert-manager/issues/4405
  # Says the only purpose is to check CRDs, which we already installed.
  startupapicheck:
    enabled: false

traefik:
  # Configure based on:
  # https://github.com/traefik/traefik-helm-chart/blob/master/traefik/values.yaml

  ports:
    # Host ports to be associated with entrypoints must also be directed from the host machine to Minikube.
    # This is configured in `ansible/ansible_minikube_ingress_ports.yaml`, currently only (80, 443, 8000, 9000).

    # Port 9000 is used by traefik itself for its internal dashboard.

    # Entrypoint for public web access via HTTP.
    # Traefik defaults to port 8000, but we will use that for the entrypoint secure. Overide to port 8080.
    web:
      port: 8080
      hostPort: 80

    # Entrypoint for public web access via HTTPS.
    websecure:
      port: 8443
      hostPort: 443
      tls:
        enabled: true

    # Entrypoint intended for ingress-configurable access to internal services.
    # Should be accessible only via an SSH tunnel forwarding port 8000.
    private:
      port: 8000
      hostPort: 8000
      exposedPort: 8000
      protocol: TCP
      expose: true
