traefik:
  # Configure based on:
  # https://github.com/traefik/traefik-helm-chart/blob/master/traefik/values.yaml

  providers:
    kubernetesCRD:
      # Allow IngressRoutes to reference resources in other namespaces.
      # This allows application routes to reference our provided middlewares.
      allowCrossNamespace: true

  ports:
    # Host ports to be associated with entrypoints must also be directed from the host machine to Minikube.
    # This is configured in `ansible/ansible_minikube_ingress_ports.yaml`, currently only (80, 443, 8000, 9000).

    # Port 9000 is used by traefik itself for its internal dashboard.

    # Entrypoint for public web access via HTTP.
    # Traefik defaults to port 8000, but we will use that for the entrypoint private. Overide to port 8080.
    web:
      port: 8080
      hostPort: 80

    # Entrypoint for public web access via HTTPS.
    websecure:
      port: 8443
      hostPort: 443
      tls:
        enabled: true

    # Entrypoint intended for ingress-configurable access to internal services.
    # Should be accessible only via an SSH tunnel forwarding port 8000.
    private:
      port: 8000
      hostPort: 8000
      exposedPort: 8000
      protocol: TCP
      expose: true
