# https://kubernetes.io/docs/concepts/services-networking/ingress/

apiVersion: 'networking.k8s.io/v1beta1'
kind: 'Ingress'
metadata:
  name: 'jenkins-ingress'
  namespace: 'jenkins'
  labels:
    app: 'jenkins'

  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: 'dashboard'

spec:
  rules:
  - http:
      paths:
      - path: '/jenkins'
        backend:
          serviceName: 'jenkins'
          servicePort: 8080
