#
# A simple helmfile that only configures ingress.
#
# Useful as a copy-paste template for starting a helmfile.
#

repositories:
  # aws-infrastructure helm repository
  #
  # When developing charts that will later be merged, it can be helpful to instead point at a branch:
  # url: 'https://raw.githubusercontent.com/<account>/aws-infrastructure/<branch>/helm_repo/'
  - name: 'aws-infrastructure'
    url: 'https://raw.githubusercontent.com/fogies/aws-infrastructure/main/helm_repo/'

releases:
  # ingress-crd contains CRDs required by cert-manager and by ingress
  - name: 'ingress-crd'
    chart: 'aws-infrastructure/ingress-crd'
    version: '0.5.0'

  # cert-manager
  - name: 'cert-manager'
    namespace: 'cert-manager'
    chart: 'aws-infrastructure/cert-manager'
    version: '1.6.1'
    needs:
      - 'ingress-crd'

  # ingress
  - name: 'ingress'
    chart: 'aws-infrastructure/ingress'
    version: '0.5.0'
    needs:
      - 'ingress-crd'

# Prefer explicit management of CRDs via releases
helmDefaults:
  args:
    - '--skip-crds'

# Prefer explicit errors
missingFileHandler: 'Error'
