jenkins:
  # Configure based on:
  # https://github.com/jenkinsci/helm-charts/blob/main/charts/jenkins/values.yaml

  # Define a global Jenkins instance
  fullnameOverride: 'jenkins'
  namespaceOverride: 'jenkins'

  controller:
    # Prefix under which Jenkins is served
    jenkinsUriPrefix: '/jenkins'

    # Run tasks on the controller
    numExecutors: 1

    # Include docker-workflow
    additionalPlugins:
      - docker-workflow:1.25
        # https://docs.cloudbees.com/docs/admin-resources/latest/plugins/docker-workflow
      - job-dsl:1.77
        # https://jenkinsci.github.io/job-dsl-plugin/

  agent:
    # Configure a pod template that includes a Docker client
    podTemplates:
      docker: |
        - name: docker
          label: docker
          serviceAccount: jenkins
          containers:
            - name: docker
              image: docker:20.10.2
              command: "/bin/sh -c"
              args: "cat"
              ttyEnabled: true
          volumes:
            - hostPathVolume:
                hostPath: /var/run/docker.sock
                mountPath: /var/run/docker.sock
