apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: 'letsencrypt'
spec:
  acme:
    # Contact for expiring certificates and account issues
    email: 'fogies-registrations@cs.washington.edu'

    # Configure for the production server
    server: 'https://acme-v02.api.letsencrypt.org/directory'
    privateKeySecretRef:
      # Secret resource used to store the account's private key.
      name: 'issuer-account-key'

    # Add a single HTTP01 challenge solver
    solvers:
    - http01:
        # Do not provide a class filter to the solver.
        # We only have one ingress executing in our cluster, so it handles the ingress.
        # Previously had problems where providing any value for ingress class resulted
        # in Traefik not picking up the Ingress needed for the solver.
        ingress: {}
