---

- name: Install Helm
  hosts: 127.0.0.1
  connection: local

  vars:
    versions:
      helm: v3.5.2
      helmdiff: v3.1.3
      helmfile: v0.138.4

  tasks:
    #
    # Install Helm
    #

    - name: Create Temporary Directory
      tempfile:
        state: directory
      register: tempdir

    - name: Download Helm Installer
      get_url:
        url: https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
        dest: "{{ tempdir.path }}/get_helm.sh"
        mode: 0700

    - name: Install Helm
      become: yes
      command:
        cmd: "{{ tempdir.path }}/get_helm.sh --version {{ versions.helm }}"

    - name: Confirm Helm Installation
      command:
        cmd: helm version

    - name: Delete Temporary Directory
      file:
        path: "{{ tempdir.path }}"
        state: absent

    #
    # Helmfile requires the helm diff plugin
    #

    - name: Install helm diff plugin
      command:
        cmd: helm plugin install --version {{ versions.helmdiff }} https://github.com/databus23/helm-diff

    #
    # Install Helmfile
    #

    - name: Download Helmfile
      become: yes
      get_url:
        url: https://github.com/roboll/helmfile/releases/download/{{ versions.helmfile }}/helmfile_linux_{{ architecture }}
        dest: /usr/local/bin/helmfile
        mode: 0755

    - name: Confirm Helmfile Installation
      command:
        cmd: helmfile --version
