---

- name: Install Helm
  hosts: 127.0.0.1
  connection: local

  vars:
    # Expected from BUILD_CONFIG:
    # - aws_instance_architecture
    # - version_helm
    # - version_helmdiff
    # - version_helmfile

  tasks:
    #
    # Install Helm
    #

    - name: Create Temporary Directory
      tempfile:
        state: directory
      register: tempdir

    - name: Download Helm Installer
      get_url:
        url: https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
        dest: "{{ tempdir.path }}/get_helm.sh"
        mode: 0700

    - name: Install Helm
      become: yes
      command:
        cmd: "{{ tempdir.path }}/get_helm.sh --version {{ version_helm }}"

    - name: Confirm Helm Installation
      command:
        cmd: helm version

    - name: Delete Temporary Directory
      file:
        path: "{{ tempdir.path }}"
        state: absent

    #
    # Helmfile requires the helm diff plugin
    #

    - name: Install helm diff plugin
      command:
        cmd: helm plugin install --version {{ version_helmdiff }} https://github.com/databus23/helm-diff

    #
    # Install Helmfile
    #

    - name: Download Helmfile
      become: yes
      get_url:
        url: https://github.com/roboll/helmfile/releases/download/{{ version_helmfile }}/helmfile_linux_{{ aws_instance_architecture }}
        dest: /usr/local/bin/helmfile
        mode: 0755

    - name: Confirm Helmfile Installation
      command:
        cmd: helmfile --version
